#!/usr/bin/env bash
#Using a while loop to display "Best School" 10 times & 'Hi' in 9th

counter=2
while [ $counter -le 10 ]
do
        if [ $counter == 9 ]
        then
                echo "Best School"
                echo "Hi"
        else
        	echo "Best School"
        fi
    ((counter++))
done
