#!/usr/bin/env bash
#A script that makes nginx run as the nginx user 
pkill apache2
chmod -R 777 /etc/nginx

# Ensure nginx is not running as root
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Update nginx configuration to listen on all active IPs on port 8080
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx nginx -c /etc/nginx/nginx.conf

