#!/usr/bin/env bash
#A script that makes nginx run as the nginx user but shrinked to 7 lines
#!/pkill apache2
chown nginx /etc/nginx/nginx.conf
chmod u+r /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
